In [16]:
import numpy as np
import pandas as pd

In [17]:
pd.set_option('display.max_colwidth', None)

In [18]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [19]:
df = pd.read_csv('land_cleaned.csv')

In [48]:
df.shape

(2174, 5)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.insert(loc = 2 , column='sector',value=df['property_name'].str.split('in').str.get(1).str.lower().str.replace('gurgaon','').str.strip())

In [ ]:
df['sector'] = df['sector'].str.replace('-',' ')

In [ ]:
df[df['sector'] == 'pathredi']

,property_name,society,sector,price,areaWithType,floor_num,open_sides,possession,features
677,Residential land / Plot in Pathredi,NaN,pathredi,1.5,(4064 sq.m.) Plot Area,NaN,1.0,Immediate,['']

In [ ]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 22')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 95B')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')

In [ ]:
df['sector'] = df['sector'].str.replace('south city 2','sector 49')
df['sector'] = df['sector'].str.replace('new sector 2','sector 2')
df['sector'] = df['sector'].str.replace('new sector 2 phase 1','sector 2')
df['sector'] = df['sector'].str.replace('badshahpur','sector 66')
df['sector'] = df['sector'].str.replace('farrukh nagar','farukhnagar')
df['sector'] = df['sector'].str.replace('new sector 2 phase 2','sector 2')
df['sector'] = df['sector'].str.replace('patodi','pataudi')
df['sector'] = df['sector'].str.replace('subhash chowk','sector 33')
df['sector'] = df['sector'].str.replace('defence colony','sector 17a')
df['sector'] = df['sector'].str.replace('mayfield garden','sector 51')
df['sector'] = df['sector'].str.replace('rajiv chowk','sector 33')
df['sector'] = df['sector'].str.replace('gwal pahari','sector 2')
df['sector'] = df['sector'].str.replace('golf course road','sector 56')
df['sector'] = df['sector'].str.replace('dwarka expressway','sector 113')
df['sector'] = df['sector'].str.replace('hilalpur','sector 68')
df['sector'] = df['sector'].str.replace('block k1 new sector 2 phase 1','sector 2')
df['sector'] = df['sector'].str.replace('acharya puri','sector 7')
df['sector'] = df['sector'].str.replace('block t new sector 2 phase 2','sector 2')
df['sector'] = df['sector'].str.replace('behrampur','sector 71')
df['sector'] = df['sector'].str.replace('v block sector 24','sector 24')
df['sector'] = df['sector'].str.replace('southern peripheral road','sector 58')
df['sector'] = df['sector'].str.replace('block g sector 57','sector 57')
df['sector'] = df['sector'].str.replace('sai kunj','sector 110a')
df['sector'] = df['sector'].str.replace('part 6 sector 5','sector 5')
df['sector'] = df['sector'].str.replace('faridabad road','sector 75')
df['sector'] = df['sector'].str.replace('huda sector','sector 46')
df['sector'] = df['sector'].str.replace('heera nagar','sector 11')
df['sector'] = df['sector'].str.replace('sector 2 colony','sector 2')
df['sector'] = df['sector'].str.replace('carterpuri village','sector 23a')
df['sector'] = df['sector'].str.replace('bhora kalan','pataudi')
df['sector'] = df['sector'].str.replace('om vihar','sector 23a')
df['sector'] = df['sector'].str.replace('cyber city','sector 24')
df['sector'] = df['sector'].str.replace('ram vihar','sector 104')
df['sector'] = df['sector'].str.replace('pataudi road','pataudi')
df['sector'] = df['sector'].str.replace('mullahera village','sector 22')
df['sector'] = df['sector'].str.replace('dhankot','sector 99')
df['sector'] = df['sector'].str.replace('vijay vihar','sector 30')
df['sector'] = df['sector'].str.replace('block c, sushant lok phase i','sector 43')
df['sector'] = df['sector'].str.replace('nihali colony','sector 110')
df['sector'] = df['sector'].str.replace('huda colony','sector 46')
df['sector'] = df['sector'].str.replace('sector 15 part 2','sector 15')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('gali no 18','sector 18')
df['sector'] = df['sector'].str.replace('jail road','sector 68')
df['sector'] = df['sector'].str.replace('raj nagar','sector 10a')
df['sector'] = df['sector'].str.replace('ansal sector 2','sector 2')
df['sector'] = df['sector'].str.replace('s block sector 24 sector 24','sector 24')
df['sector'] = df['sector'].str.replace('bptp amstoria sector 102, gurugram','sector 102')
df['sector'] = df['sector'].str.replace('block n sector 51','sector 51')
df['sector'] = df['sector'].str.replace('huda rwa sector 47','sector 47')
df['sector'] = df['sector'].str.replace('orris aanandam ora sector 93','sector 93')
df['sector'] = df['sector'].str.replace('orris aanandam ora','sector 93')
df['sector'] = df['sector'].str.replace('rajiv colony','sector 33')
df['sector'] = df['sector'].str.replace('d block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 15 part 1','sector 15')
df['sector'] = df['sector'].str.replace('block m sector 41','sector 41')
df['sector'] = df['sector'].str.replace('block b1 sector 57','sector 57')
df['sector'] = df['sector'].str.replace('block a sector 41','sector 41')
df['sector'] = df['sector'].str.replace('sec 54 sector 54','sector 54')
df['sector'] = df['sector'].str.replace('block j sector 41','sector 41')
df['sector'] = df['sector'].str.replace('dlf garden city, sector 91','sector 91')
df['sector'] = df['sector'].str.replace('huda sector 42','sector 42')

In [ ]:
df['sector'] = df['sector'].str.replace('part 6 sector 5','sector 5')
df['sector'] = df['sector'].str.replace('block t sector 2 phase 2','sector 2')
df['sector'] = df['sector'].str.replace('orris aanadam ora sector 93','sector 93')
df['sector'] = df['sector'].str.replace('moulsari avenve road sector 24','sector 24')
df['sector'] = df['sector'].str.replace('sector 1 pataudi','pataudi')

In [ ]:
df['sector'] = df['sector'].str.replace('shona','sohna')

In [ ]:
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 67')

In [ ]:
df['sector'] = df['sector'].str.replace('sector 33 sohna road','sector 33 shona')
df['sector'] = df['sector'].str.replace('sector 35 sohna road','sector 35 shona')
df['sector'] = df['sector'].str.replace('sector 5 sohna road','sector 5 shona')
df['sector'] = df['sector'].str.replace('sector 2 sohna road','sector 2 shona')
df['sector'] = df['sector'].str.replace('sector 4 sohna road','sector 4 shona')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36 shona')
df['sector'] = df['sector'].str.replace('sector 11 sohna road','sector 11 shona')
df['sector'] = df['sector'].str.replace('sector 22 sohna road','sector 22 shona')
df['sector'] = df['sector'].str.replace('sector 7 sohna road','sector 7 shona')
df['sector'] = df['sector'].str.replace('sohna road road','shona road')

In [ ]:
counts = df['sector'].value_counts()

valid_sectors = counts[counts > 1].index

df = df[df['sector'].isin(valid_sectors)]

In [12]:
def extract_area(x):
    area = x.split('sq.m.')[0].replace('(','').strip()

    if '-' in area:
        a, b = area.split('-')
        return (float(a) + float(b)) / 2

    return float(area)

In [23]:
df.insert(loc=3,column = 'area',value=df['areaWithType'].apply(extract_area))

In [33]:
df['open_sides'] = df['open_sides'].fillna(
    df.groupby('sector')['open_sides'].transform('median')
)

In [34]:
df['open_sides'] = df['open_sides'].fillna(df['open_sides'].median())

In [36]:
df = df[df['price'].notna()]

df.drop(
    columns=['areaWithType', 'floor_num', 'society', 'possession'],
    inplace=True
)

/tmp/ipykernel_4542/3811215739.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(

In [39]:
df['features'].value_counts()

features
[['Feng Shui / Vaastu Compliant', 'Maintenance Staff', 'Water Storage', 'Rain Water Harvesting']]    738
['']                                                                                                 241
[['Maintenance Staff', 'Water Storage', 'Rain Water Harvesting']]                                    184
[['Maintenance Staff']]                                                                              111
[['Feng Shui / Vaastu Compliant']]                                                                    73
[['Water Storage']]                                                                                   51
[['Maintenance Staff', 'Water Storage']]                                                              48
[['Feng Shui / Vaastu Compliant', 'Maintenance Staff']]                                               47
[['Feng Shui / Vaastu Compliant', 'Maintenance Staff', 'Water Storage']]                              44
[['Feng Shui / Vaastu Compliant', 'Water Storage', 'Rain Water Harvesting']]                          44
[['Maintenance Staff', 'Rain Water Harvesting']]                                                      42
[['Feng Shui / Vaastu Compliant', 'Maintenance Staff', 'Rain Water Harvesting']]                      41
[['Rain Water Harvesting']]                                                                           40
[['Water Storage', 'Rain Water Harvesting']]                                                          24
['Feng Shui / Vaastu Compliant', 'Maintenance Staff', 'Water Storage', 'Rain Water Harvesting']       21
[['Feng Shui / Vaastu Compliant', 'Rain Water Harvesting']]                                           21
[['Feng Shui / Vaastu Compliant', 'Water Storage']]                                                   12
['Water Storage', 'Rain Water Harvesting']                                                             5
['Maintenance Staff', 'Water Storage', 'Rain Water Harvesting']                                        5
['Maintenance Staff']                                                                                  5
['Water Storage']                                                                                      5
['Feng Shui / Vaastu Compliant']                                                                       4
['Feng Shui / Vaastu Compliant', 'Rain Water Harvesting']                                              3
['Feng Shui / Vaastu Compliant', 'Water Storage']                                                      2
['Feng Shui / Vaastu Compliant', 'Water Storage', 'Rain Water Harvesting']                             2
['Feng Shui / Vaastu Compliant', 'Maintenance Staff', 'Rain Water Harvesting']                         2
['Rain Water Harvesting']                                                                              2
['Maintenance Staff', 'Water Storage']                                                                 1
['Feng Shui / Vaastu Compliant', 'Maintenance Staff', 'Water Storage']                                 1
['Feng Shui / Vaastu Compliant', 'Maintenance Staff']                                                  1
[['Feng Shui / Vaastu Compliant', 'Water Storage', 'Maintenance Staff', 'Rain Water Harvesting']]      1
[['Visitor Parking']]                                                                                  1
Name: count, dtype: int64

In [40]:
def feature_score(x):
    if pd.isna(x):
        return 0

    score = 0

    if 'Feng Shui' in x:
        score += 1
    if 'Maintenance Staff' in x:
        score += 1
    if 'Water Storage' in x:
        score += 1
    if 'Rain Water Harvesting' in x:
        score += 1

    return score

df['feature_score'] = df['features'].apply(feature_score)

/tmp/ipykernel_4542/589623434.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['feature_score'] = df['features'].apply(feature_score)

In [42]:
def feature_category(score):
    if score == 0:
        return 'Basic'
    elif score <= 2:
        return 'Standard'
    else:
        return 'Premium'

df['feature'] = df['feature_score'].apply(feature_category)

/tmp/ipykernel_4542/2585966565.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['feature'] = df['feature_score'].apply(feature_category)

In [43]:
df['feature'].value_counts()

feature
Premium     1083
Basic        594
Standard     497
Name: count, dtype: int64

In [45]:
df.drop(columns=['features','feature_score','property_name'],inplace=True)

/tmp/ipykernel_4542/165741594.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['features','feature_score','property_name'],inplace=True)

In [54]:
df['sector'].value_counts()

sector
sohna road          104
sector 43           103
sector 102           99
sector 2             82
sector 33 sohna      77
sector 57            73
sector 108           71
sector 25            58
sector 67            57
sector 88a           53
sector 26            52
sector 45            50
sector 99            47
sector 46            46
sector 99a           45
sector 88b           41
sector 70a           41
sector 95            38
sector 83            37
sector 52            36
sector 41            36
sector 28            34
sector 42            34
sector 73            33
sector 47            31
sector 55            30
sector 35 sohna      28
sector 49            28
sector 38            27
sector 24            26
sector 91            26
sector 51            25
sector 65            25
sector 50            24
sector 78            20
sector 89            19
sector 11            18
farukhnagar          17
sector 66            17
sector 7             16
sector 93            16
sector 112           16
pataudi              16
sector 23            15
sector 67a           14
sector 56            14
sector 9             13
sector 40            13
sector 4             12
sector 48            12
sector 22            12
sector 82a           10
sector 5 sohna       10
sector 9a            10
sector 33            10
sector 63             9
sector 39             9
sector 60             9
sector 2 sohna        9
sector 2 phase 1      9
sector 54             9
sector 85             9
sector 27             8
sector 82             8
sector 95B            8
sector 92             8
sector 105            8
sector 10             7
sector 10a            7
sector 95a            7
sector 35             6
sector 15             6
sector 88             5
sector 106            5
sector 68             5
sector 30             5
sector 63a            5
sector 12             5
sector 23a            4
sector 69             4
sector 110 a          4
sultanpur             4
sector 3              4
sector 5              4
sector 17a            4
sector 37d            3
sector 62             3
sector 113            3
sector 17             3
sector 12a            3
sector 22b            3
sector 21             3
sector 81a            2
jhajjar               2
new                   2
sector 90             2
sidhrawali            2
vr                    2
sector 53             2
sector 103            2
part  6 sector 5      2
sector 110            2
sector 4 sohna        2
sector 75             2
sector 36 sohna       2
sector 14             2
manesar               2
sector 58             2
sector 79             2
sector 31             2
sector 110a           2
sector 70             2
sector 71             2
Name: count, dtype: int64

In [52]:
block k1 sector 2 phase 1	 , part 6 sector 5 , vr , jhajjar , new

SyntaxError: invalid syntax (3711135293.py, line 1)

In [69]:
df['sector'].value_counts()

sector
sohna road         104
sector 43          103
sector 102          99
sector 2            91
sector 33 sohna     77
sector 57           73
sector 108          71
sector 25           58
sector 67           57
sector 88a          53
sector 26           52
sector 45           50
sector 99           47
sector 46           46
sector 99a          45
sector 88b          41
sector 70a          41
sector 95           38
sector 83           37
sector 41           36
sector 52           36
sector 42           34
sector 28           34
sector 73           33
sector 47           31
sector 55           30
sector 35 sohna     28
sector 49           28
sector 38           27
sector 24           26
sector 91           26
sector 51           25
sector 65           25
sector 50           24
sector 78           20
sector 89           19
sector 11           18
sector 66           17
farukhnagar         17
pataudi             16
sector 112          16
sector 93           16
sector 7            16
sector 23           15
sector 56           14
sector 67a          14
sector 40           13
sector 9            13
sector 22           12
sector 4            12
sector 48           12
sector 5 sohna      10
sector 82a          10
sector 33           10
sector 9a           10
sector 54            9
sector 60            9
sector 2 sohna       9
sector 39            9
sector 63            9
sector 85            9
sector 27            8
sector 82            8
sector 105           8
sector 92            8
sector 95b           8
sector 95a           7
sector 10a           7
sector 10            7
sector 35            6
sector 5             6
sector 15            6
sector 30            5
sector 12            5
sector 68            5
sector 63a           5
sector 88            5
sector 106           5
sultanpur            4
sector 17a           4
sector 23a           4
sector 3             4
sector 110 a         4
sector 69            4
sector 37d           3
sector 17            3
sector 21            3
sector 62            3
sector 113           3
sector 22b           3
sector 12a           3
sidhrawali           2
sector 53            2
sector 81a           2
sector 103           2
sector 90            2
sector 4 sohna       2
sector 75            2
sector 36 sohna      2
sector 110           2
sector 14            2
manesar              2
sector 58            2
sector 79            2
sector 31            2
sector 110a          2
sector 70            2
sector 71            2
Name: count, dtype: int64

In [70]:
df.to_csv('final_clean_land.csv')